package com.example.deviceinfo.feature.devcompare

import android.app.ActivityManager; import android.content.Context; import android.os.*; import android.view.*
import android.widget.*; import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment

data class PhoneSpec(val name: String, val ramGb: Float, val storageGb: Float, val battMah: Int, val camMp: Float, val displayInch: Float, val cpuScore: Int)

val PHONE_DB = listOf(
    PhoneSpec("Samsung S24 Ultra",12f,256f,5000,200f,6.8f,100),
    PhoneSpec("Samsung S24",8f,128f,4000,50f,6.2f,92),
    PhoneSpec("iPhone 16 Pro",8f,128f,3582,48f,6.3f,110),
    PhoneSpec("iPhone 16",8f,128f,3561,48f,6.1f,105),
    PhoneSpec("Pixel 9 Pro",16f,128f,4700,50f,6.3f,98),
    PhoneSpec("Pixel 9",12f,128f,4700,50f,6.3f,95),
    PhoneSpec("OnePlus 12",16f,256f,5400,50f,6.82f,96),
    PhoneSpec("Xiaomi 14 Ultra",16f,512f,5000,50f,6.73f,99),
    PhoneSpec("Xiaomi 14",12f,256f,4610,50f,6.36f,94),
    PhoneSpec("Redmi Note 13 Pro",12f,256f,5100,200f,6.67f,72),
    PhoneSpec("Samsung A55",8f,128f,5000,50f,6.6f,70),
    PhoneSpec("Nothing Phone 2",12f,256f,4700,50f,6.7f,85),
    PhoneSpec("Motorola Edge 50",12f,256f,4700,50f,6.7f,80),
    PhoneSpec("Vivo X100 Pro",16f,512f,5400,50f,6.78f,97),
    PhoneSpec("Oppo Reno 12 Pro",12f,256f,5000,50f,6.7f,75)
)

class DeviceCompareFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: DeviceCompareGroupedBar?=null
    private var tvYour: TextView?=null; private var selectedPhone: PhoneSpec?=null

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="📊 Device Comparison";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        tvYour=TextView(requireContext()).apply{textSize=11f;setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvYour)
        val spinner=Spinner(requireContext()); val items=PHONE_DB.map{it.name}
        spinner.adapter=ArrayAdapter(requireContext(),android.R.layout.simple_spinner_dropdown_item,items)
        spinner.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{
            override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){selectedPhone=PHONE_DB[pos];updateChart()}
            override fun onNothingSelected(p:AdapterView<*>?){}
        }
        root.addView(spinner)
        chart=DeviceCompareGroupedBar(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(300))}
        root.addView(chart)
        val am=requireContext().getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val mi=ActivityManager.MemoryInfo().also{am.getMemoryInfo(it)}
        tvYour?.text="Your device — RAM: ${"%.0f".format(mi.totalMem/1073741824f)}GB  Build: ${Build.MODEL}"
        selectedPhone=PHONE_DB[0]; updateChart()
        return scroll
    }

    private fun updateChart() {
        val sp=selectedPhone?:return
        val am=requireContext().getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val mi=ActivityManager.MemoryInfo().also{am.getMemoryInfo(it)}
        val ramGb=mi.totalMem/1073741824f
        val storGb=android.os.Environment.getDataDirectory().let{android.os.StatFs(it.path)}.let{sf->sf.blockSizeLong*sf.blockCountLong/1073741824f}
        val metrics=listOf(
            DeviceCompareGroupedBar.MetricPair("RAM",ramGb,sp.ramGb,20f,"GB"),
            DeviceCompareGroupedBar.MetricPair("Storage",storGb,sp.storageGb.toFloat(),1024f,"GB"),
            DeviceCompareGroupedBar.MetricPair("Battery",5000f,sp.battMah.toFloat(),6000f,"mAh"),
            DeviceCompareGroupedBar.MetricPair("Camera",50f,sp.camMp,200f,"MP"),
            DeviceCompareGroupedBar.MetricPair("Display",6.1f,sp.displayInch,7f,"\""),
            DeviceCompareGroupedBar.MetricPair("CPU Score",80f,sp.cpuScore.toFloat(),110f,"pt")
        )
        chart?.setMetrics(metrics)
    }

    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }
    override fun getShareText()="Device Comparison: Your device vs ${selectedPhone?.name}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
