package com.example.deviceinfo.feature.loadavg

import android.os.*; import android.view.*; import android.widget.*; import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment; import java.io.BufferedReader; import java.io.FileReader

class LoadAvgFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: LoadAvgTripleChart?=null; private var tvInfo: TextView?=null
    private val handler=Handler(Looper.getMainLooper())
    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;update();handler.postDelayed(this,3000L)}}

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="📈 System Load Average";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Red zone = overloaded  |  1×cores = 100% busy";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=LoadAvgTripleChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(220))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvInfo)
        update()
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun update() {
        try {
            val line=BufferedReader(FileReader("/proc/loadavg")).use{it.readLine()} ?: return
            val parts=line.trim().split(" ")
            val l1=parts[0].toFloatOrNull()?:0f; val l5=parts[1].toFloatOrNull()?:0f; val l15=parts[2].toFloatOrNull()?:0f
            val cores=Runtime.getRuntime().availableProcessors()
            val uptime=try{BufferedReader(FileReader("/proc/uptime")).use{it.readLine()?.split(" ")?.get(0)?.toFloatOrNull()?:0f}}catch(_:Exception){0f}
            chart?.add(l1,l5,l15)
            val status=when{l1>cores*1.5f->"🔴 OVERLOADED";l1>cores*1.0f->"🟠 High Load";l1>cores*0.5f->"🟡 Moderate";else->"🟢 Idle"}
            tvInfo?.text="Load: $l1 / $l5 / $l15  (1/5/15 min)
Cores: $cores  |  Load per core: ${"%.2f".format(l1/cores)}
Status: $status
Uptime: ${"%.0f".format(uptime/3600)}h ${"%.0f".format((uptime%3600)/60)}m"
        } catch(_:Exception){}
    }

    override fun getShareText()="Load Average
${tvInfo?.text}
Generated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
