package com.cpua.deviceinfo.feature.throttle

import android.os.*; import android.view.*; import android.widget.*; import androidx.fragment.app.Fragment
import com.cpua.deviceinfo.core.ui.ShareableFragment; import java.io.BufferedReader; import java.io.FileReader

class ThrottleFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null; private var chart: ThrottleAnnotatedChart? = null; private var tvStats: TextView? = null
    private val handler = Handler(Looper.getMainLooper())
    private val runnable = object : Runnable {
        override fun run() { if (rootView == null) return; update(); handler.postDelayed(this, 2000L) }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll = ScrollView(requireContext()); val root = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.VERTICAL; val p = dp(12); setPadding(p, p, p, p) }
        scroll.addView(root); rootView = scroll
        root.addView(TextView(requireContext()).apply { text = "🔥 Thermal Throttle Detector"; textSize = 16f
            setTypeface(null, android.graphics.Typeface.BOLD); setPadding(0, 0, 0, dp(6)) })
        root.addView(TextView(requireContext()).apply { text = "Orange=Temperature  Blue=CPU Freq%  Red shading=Throttle event"; textSize = 11f; alpha = 0.7f; setPadding(0,0,0,dp(4)) })
        chart = ThrottleAnnotatedChart(requireContext()).apply {
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(220)) }
        root.addView(chart)
        tvStats = TextView(requireContext()).apply { textSize = 12f; setPadding(0, dp(8), 0, 0); setTextColor(0xFFCCCCCC.toInt()) }
        root.addView(tvStats)
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView = null; chart = null }

    private fun update() {
        val tempC = readBatteryTemp()
        val (curFreq, maxFreq) = readCpuFreq()
        val freqPct = if (maxFreq > 0) (curFreq * 100f / maxFreq).coerceIn(0f, 100f) else 0f
        // Throttle heuristic: freq < 60% of max AND temp > 42°C
        val throttled = freqPct < 60f && tempC > 42f
        chart?.add(tempC, freqPct, throttled)
        tvStats?.text = "CPU: ${"%.0f".format(freqPct)}% (${curFreq/1000}MHz / ${maxFreq/1000}MHz)\nTemp: ${"%.1f".format(tempC)}°C\nThrottle events: ${chart?.getThrottleCount() ?: 0}\nStatus: ${if(throttled)"⚠️ THROTTLING" else "✅ Normal"}"
    }

    private fun readBatteryTemp(): Float {
        return try {
            val f = IntentFilter(android.content.Intent.ACTION_BATTERY_CHANGED)
            val i = requireContext().registerReceiver(null, f)
            (i?.getIntExtra(android.os.BatteryManager.EXTRA_TEMPERATURE, 250) ?: 250) / 10f
        } catch (_: Exception) { 35f }
    }
    private fun IntentFilter(action: String) = android.content.IntentFilter(action)

    private fun readCpuFreq(): Pair<Long, Long> {
        return try {
            val cur = BufferedReader(FileReader("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq")).use { it.readLine()?.toLongOrNull() ?: 0L }
            val max = BufferedReader(FileReader("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")).use { it.readLine()?.toLongOrNull() ?: 1L }
            cur to max
        } catch (_: Exception) { 0L to 1L }
    }

    override fun getShareText() = "Thermal Throttle Detector\n${tvStats?.text}\nGenerated by CPU-A"
    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()
}
