package com.example.deviceinfo.feature.sensorlive

import android.hardware.*; import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment

class SensorLiveFragment : Fragment(), ShareableFragment, SensorEventListener {
    private var rootView: View?=null; private var sm: SensorManager?=null
    private val gauges = mutableMapOf<Int,SensorNeedleGauge>()
    private val handler=Handler(Looper.getMainLooper())

    data class GaugeDef(val type: Int, val label: String, val min: Float, val max: Float, val color: Int, val axis: Int=0)
    private val defs = listOf(
        GaugeDef(Sensor.TYPE_ACCELEROMETER,   "Accel X (m/s²)", -20f, 20f, 0xFF4CAF50.toInt(), 0),
        GaugeDef(Sensor.TYPE_ACCELEROMETER,   "Accel Y (m/s²)", -20f, 20f, 0xFF2196F3.toInt(), 1),
        GaugeDef(Sensor.TYPE_GYROSCOPE,        "Gyro X (°/s)",  -10f, 10f, 0xFFFF9800.toInt(), 0),
        GaugeDef(Sensor.TYPE_GYROSCOPE,        "Gyro Y (°/s)",  -10f, 10f, 0xFFF44336.toInt(), 1),
        GaugeDef(Sensor.TYPE_MAGNETIC_FIELD,   "Mag X (µT)",    -100f,100f, 0xFF9C27B0.toInt(), 0),
        GaugeDef(Sensor.TYPE_LIGHT,            "Light (lux)",    0f, 10000f,0xFF00BCD4.toInt(), 0)
    )

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="🧭 Sensor Live Dashboard";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        val grid=GridLayout(requireContext()).apply{columnCount=2;rowCount=3;useDefaultMargins=true}
        defs.forEachIndexed{idx,def->
            val g=SensorNeedleGauge(requireContext()).apply{
                setup(def.label,def.min,def.max,def.color)
                layoutParams=GridLayout.LayoutParams().apply{width=dp(160);height=dp(160);setMargins(dp(4),dp(4),dp(4),dp(4))}
            }
            gauges[idx]=g; grid.addView(g)
        }
        root.addView(grid)
        sm=requireContext().getSystemService(android.content.Context.SENSOR_SERVICE) as SensorManager
        return scroll
    }

    override fun onResume() {
        super.onResume()
        val sensors=setOf(Sensor.TYPE_ACCELEROMETER,Sensor.TYPE_GYROSCOPE,Sensor.TYPE_MAGNETIC_FIELD,Sensor.TYPE_LIGHT)
        sensors.forEach{t->sm?.getDefaultSensor(t)?.let{sm?.registerListener(this,it,SensorManager.SENSOR_DELAY_UI)}}
    }
    override fun onPause() { super.onPause(); sm?.unregisterListener(this) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null }
    override fun onAccuracyChanged(s: Sensor?, a: Int) {}
    override fun onSensorChanged(event: SensorEvent?) {
        if(event==null) return
        handler.post {
            if(rootView==null)return@post
            defs.forEachIndexed{idx,def->
                if(def.type==event.sensor.type && def.axis<event.values.size) {
                    gauges[idx]?.setValue(event.values[def.axis])
                }
            }
        }
    }
    override fun getShareText()="Sensor Live Dashboard\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
