package com.example.deviceinfo.feature.cpuheatmap

import android.os.*; import android.view.*; import android.widget.*; import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment; import java.io.BufferedReader; import java.io.FileReader

class CpuHeatmapFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null; private var heatmap: CpuHeatmapView? = null; private var tvInfo: TextView? = null
    private val handler = Handler(Looper.getMainLooper())
    private val runnable = object : Runnable {
        override fun run() { if (rootView == null) return; updateFreqs(); handler.postDelayed(this, 1000L) }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll = ScrollView(requireContext()); val root = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.VERTICAL; val p = dp(12); setPadding(p, p, p, p) }
        scroll.addView(root); rootView = scroll
        root.addView(TextView(requireContext()).apply { text = "🌡 CPU Frequency Heatmap"; textSize = 16f
            setTypeface(null, android.graphics.Typeface.BOLD); setPadding(0, 0, 0, dp(6)) })
        root.addView(TextView(requireContext()).apply { text = "Blue=Low  Green=Mid  Red=High freq  (updated every 1s)"; textSize = 11f; alpha = 0.7f; setPadding(0, 0, 0, dp(4)) })
        heatmap = CpuHeatmapView(requireContext()).apply {
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(240)) }
        root.addView(heatmap)
        tvInfo = TextView(requireContext()).apply { textSize = 11f; setPadding(0, dp(6), 0, 0); setTextColor(0xFFAAAAAA.toInt()) }
        root.addView(tvInfo)
        // Set max freq
        val maxKhz = try { BufferedReader(FileReader("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")).use { it.readLine()?.toLongOrNull() ?: 2000000L } } catch (_: Exception) { 2000000L }
        heatmap?.setMaxFreq(maxKhz)
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView = null; heatmap = null }

    private fun updateFreqs() {
        val freqs = mutableListOf<Long>()
        for (cpu in 0..7) {
            try { BufferedReader(FileReader("/sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_cur_freq")).use {
                freqs.add(it.readLine()?.toLongOrNull() ?: 0L) } } catch (_: Exception) { break }
        }
        heatmap?.pushSample(freqs)
        tvInfo?.text = freqs.mapIndexed { i, f -> "C$i:${f/1000}MHz" }.joinToString("  ")
    }

    override fun getShareText() = "CPU Frequency Heatmap — ${Runtime.getRuntime().availableProcessors()} cores\nGenerated by CPU-A"
    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()
}
