pluginManagement {
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = "DeviceInfo"
include(":app")
include(":core")
include(":feature-soc")
include(":feature-device")
include(":feature-system")
include(":feature-battery")
include(":feature-thermal")
include(":feature-sensors")
include(":feature-about")
include(":feature-network")
include(":feature-camera")
include(":feature-audio")
include(":feature-display")
include(":feature-codec")
include(":feature-benchmark")
include(":feature-connectivity")
include(":feature-power")
include(":feature-gpu")
include(":feature-memory")
include(":feature-security")
include(":feature-input")
include(":feature-favorites")
include(":feature-health")
// Advanced Feature Modules (Policy Compliant)
include(":feature-cpucore")
include(":feature-chargesession")
include(":feature-pingmonitor")
include(":feature-screentime")
include(":feature-dischargerate")
include(":feature-cpuheatmap")
include(":feature-throttle")
include(":feature-loadavg")
include(":feature-chargecurve")
include(":feature-sensorlive")
include(":feature-devcompare")
include(":feature-powerestimate")
include(":feature-brightness")
include(":feature-bootspeed")
include(":feature-featurematrix")
