package com.example.deviceinfo.feature.storageio

import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment
import java.io.*; import java.util.concurrent.Executors

class StorageIoFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null
    private var chart: StorageIoChart? = null
    private var tvInfo: TextView? = null
    private val executor = Executors.newSingleThreadExecutor()
    private val handler  = Handler(Looper.getMainLooper())
    private var prevRead = 0L; private var prevWrite = 0L; private var prevTs = 0L

    private val runnable = object : Runnable {
        override fun run() { if (rootView==null) return; readStats(); handler.postDelayed(this,2000L) }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{
            orientation=LinearLayout.VERTICAL; val p=dp(12); setPadding(p,p,p,p) }
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{ text="💾 Storage I/O Monitor"; textSize=16f
            setTypeface(null,android.graphics.Typeface.BOLD); setPadding(0,0,0,dp(6)) })
        chart=StorageIoChart(requireContext()).apply{
            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(220)) }
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{ textSize=12f; setPadding(0,dp(8),0,0); setTextColor(0xFFCCCCCC.toInt()) }
        root.addView(tvInfo)
        root.addView(TextView(requireContext()).apply{ text="Green = Read  |  Red = Write"; textSize=11f; alpha=0.6f })
        readStats()
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun readStats() {
        executor.submit {
            var rBytes=0L; var wBytes=0L
            try {
                BufferedReader(FileReader("/proc/diskstats")).use { reader ->
                    reader.lineSequence().forEach { line ->
                        val parts=line.trim().split("\s+".toRegex())
                        if (parts.size>=14) { rBytes+=parts[5].toLongOrNull()?:0L; wBytes+=parts[9].toLongOrNull()?:0L }
                    }
                }
            } catch (_:Exception) {}
            val now=System.currentTimeMillis()
            val elapsed=((now-prevTs)/1000f).coerceAtLeast(0.1f)
            val rMbps=if(prevTs>0) ((rBytes-prevRead)*512f/(1024f*1024f*elapsed)) else 0f
            val wMbps=if(prevTs>0) ((wBytes-prevWrite)*512f/(1024f*1024f*elapsed)) else 0f
            prevRead=rBytes; prevWrite=wBytes; prevTs=now
            handler.post {
                if (rootView==null) return@post
                chart?.add(rMbps.coerceAtLeast(0f), wMbps.coerceAtLeast(0f))
                tvInfo?.text="Read: ${"%.2f".format(rMbps)} MB/s   Write: ${"%.2f".format(wMbps)} MB/s
Internal storage: ${android.os.Environment.getExternalStorageDirectory()?.path}"
            }
        }
    }

    override fun getShareText()="Storage I/O Monitor
Read: ${tvInfo?.text}
Generated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
