package com.cpua.deviceinfo.feature.screentime

import android.content.*; import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment
import com.cpua.deviceinfo.core.ui.ShareableFragment

class ScreenTimeFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null; private var chart: ScreenTimeDayBarChart? = null
    private var tvToday: TextView? = null; private var screenOnTime = 0L
    private var screenOnStart = 0L
    private val handler=Handler(Looper.getMainLooper())

    private val receiver = object : BroadcastReceiver() {
        override fun onReceive(ctx: Context?, intent: Intent?) {
            when (intent?.action) {
                Intent.ACTION_SCREEN_ON  -> { screenOnStart=System.currentTimeMillis() }
                Intent.ACTION_SCREEN_OFF -> {
                    if (screenOnStart>0) {
                        val dur=System.currentTimeMillis()-screenOnStart
                        ScreenTimeManager.addScreenOnTime(requireContext(),dur)
                        screenOnStart=0; refresh()
                    }
                }
            }
        }
    }

    private val tickRunnable=object:Runnable{override fun run(){if(rootView==null)return;refresh();handler.postDelayed(this,10_000L)}}

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{
            orientation=LinearLayout.VERTICAL; val p=dp(12); setPadding(p,p,p,p) }
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="📱 Screen-On Time Tracker";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        chart=ScreenTimeDayBarChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(200))}
        root.addView(chart)
        tvToday=TextView(requireContext()).apply{textSize=13f;setPadding(0,dp(10),0,0)}
        root.addView(tvToday)
        root.addView(TextView(requireContext()).apply{text="Green bar = Today  |  Recorded via Screen ON/OFF events";textSize=11f;alpha=0.6f;setPadding(0,dp(4),0,0)})
        refresh()
        return scroll
    }

    override fun onResume() {
        super.onResume()
        val f=IntentFilter().apply{addAction(Intent.ACTION_SCREEN_ON);addAction(Intent.ACTION_SCREEN_OFF)}
        requireContext().registerReceiver(receiver,f)
        screenOnStart=System.currentTimeMillis()
        handler.post(tickRunnable)
    }

    override fun onPause() {
        super.onPause()
        handler.removeCallbacks(tickRunnable)
        if(screenOnStart>0){ScreenTimeManager.addScreenOnTime(requireContext(),System.currentTimeMillis()-screenOnStart);screenOnStart=0}
        try{requireContext().unregisterReceiver(receiver)}catch(_:Exception){}
    }

    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun refresh() {
        val ctx=context?:return
        val data=ScreenTimeManager.getLast7Days(ctx)
        chart?.setData(data)
        val today=ScreenTimeManager.todayMs(ctx)
        tvToday?.text="Today: ${ScreenTimeManager.formatMs(today)}\n7-day avg: ${ScreenTimeManager.formatMs(data.map{it.second}.filter{it>0}.let{if(it.isEmpty())0L else it.average().toLong()})}"
    }

    override fun getShareText()="Screen-On Time: ${tvToday?.text}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
