package com.cpua.deviceinfo.feature.chargecurve

import android.content.*; import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment; import com.cpua.deviceinfo.core.ui.ShareableFragment
import kotlin.math.abs

class ChargeCurveFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: ChargeCurveDualAxisChart?=null; private var tvInfo: TextView?=null
    private val handler=Handler(Looper.getMainLooper())
    private val receiver=object:BroadcastReceiver(){
        override fun onReceive(ctx: Context?,intent:Intent?){
            val status=intent?.getIntExtra(BatteryManager.EXTRA_STATUS,-1)?:return
            val isCharging=status==BatteryManager.BATTERY_STATUS_CHARGING||status==BatteryManager.BATTERY_STATUS_FULL
            if(!isCharging){tvInfo?.text="Not charging — plug in to see curve";return}
            val level=intent.getIntExtra(BatteryManager.EXTRA_LEVEL,-1)
            val scale=intent.getIntExtra(BatteryManager.EXTRA_SCALE,100)
            val pct=if(level>=0&&scale>0)level*100/scale else 0
            val temp=(intent.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0)/10f)
            val voltage=intent.getIntExtra(BatteryManager.EXTRA_VOLTAGE,0)
            val bm=ctx?.getSystemService(Context.BATTERY_SERVICE) as? BatteryManager
            val current=abs(bm?.getIntProperty(BatteryManager.BATTERY_PROPERTY_CURRENT_NOW)?:0)/1000
            chart?.add(ChargeCurveDualAxisChart.Sample(temp,voltage,current,pct))
            tvInfo?.text="Charging: $pct%  |  ${voltage}mV  |  ${"%.1f".format(temp)}°C  |  ${current}mA\nPower: ${"%.2f".format(current*voltage/1_000_000f)}W"
        }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="⚡ Battery Charging Curve";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Blue=Voltage  Orange=Temp  Green(dash)=Current";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=ChargeCurveDualAxisChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(220))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt());text="Plug in your device to start recording"}
        root.addView(tvInfo)
        val btnClear=Button(requireContext()).apply{text="Clear Curve";setOnClickListener{chart?.clear()}}
        root.addView(btnClear)
        return scroll
    }
    override fun onResume(){super.onResume();requireContext().registerReceiver(receiver,IntentFilter(Intent.ACTION_BATTERY_CHANGED))}
    override fun onPause(){super.onPause();try{requireContext().unregisterReceiver(receiver)}catch(_:Exception){}}
    override fun onDestroyView(){super.onDestroyView();rootView=null;chart=null}
    override fun getShareText()="Charging Curve\n${tvInfo?.text}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
