package com.example.deviceinfo.feature.appmemory

import android.app.ActivityManager; import android.content.Context; import android.os.*
import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment
import java.util.concurrent.Executors

class AppMemoryFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null; private var chart: AppMemoryBarChart? = null
    private var tvTotal: TextView? = null; private val executor=Executors.newSingleThreadExecutor()
    private val handler=Handler(Looper.getMainLooper())
    private var latestEntries = listOf<AppMemoryBarChart.AppMemEntry>()

    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;loadData();handler.postDelayed(this,5000L)}}

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{
            orientation=LinearLayout.VERTICAL; val p=dp(12); setPadding(p,p,p,p) }
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="📊 App Memory Usage";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        chart=AppMemoryBarChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(300))}
        root.addView(chart)
        tvTotal=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvTotal)
        val btnRefresh=Button(requireContext()).apply{text="Refresh";setOnClickListener{loadData()}}
        root.addView(btnRefresh)
        loadData()
        return scroll
    }

    override fun onResume() { super.onResume(); handler.post(runnable) }
    override fun onPause()  { super.onPause();  handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun loadData() {
        val ctx=requireContext().applicationContext
        executor.submit {
            val am=ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
            val procs=am.runningAppProcesses ?: emptyList()
            val mi=ActivityManager.MemoryInfo().also{am.getMemoryInfo(it)}
            val memInfos=am.getProcessMemoryInfo(procs.map{it.pid}.toIntArray())
            val entries=procs.mapIndexed{i,p->
                val kb=if(i<memInfos.size)memInfos[i].totalPss else 0
                AppMemoryBarChart.AppMemEntry(p.processName.substringAfterLast('.'), kb/1024f)
            }.sortedByDescending{it.mb}.take(10)
            handler.post {
                if(rootView==null)return@post
                chart?.setEntries(entries); latestEntries=entries
                val usedMb=(mi.totalMem-mi.availMem)/1048576; val totalMb=mi.totalMem/1048576
                tvTotal?.text="System RAM: ${usedMb}MB used / ${totalMb}MB total  (${mi.availMem/1048576}MB free)\nTop apps by memory:"
            }
        }
    }

    override fun getShareText()="App Memory\n"+latestEntries.joinToString("\n"){"${it.name}: ${"%.0f".format(it.mb)}MB"}+"\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
