package com.example.deviceinfo.feature.nettraffic

import android.content.Context; import android.net.TrafficStats; import android.os.*; import android.view.*
import android.widget.*; import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment
import java.util.concurrent.Executors

class NetTrafficFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: NetTrafficDoughnutChart?=null; private var tvInfo: TextView?=null
    private val executor=Executors.newSingleThreadExecutor(); private val handler=Handler(Looper.getMainLooper())
    private var latestEntries=listOf<NetTrafficDoughnutChart.AppTraffic>()
    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;loadData();handler.postDelayed(this,5000L)}}

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="🌐 Network Traffic per App";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Top 5 apps by total data usage (since device boot)";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=NetTrafficDoughnutChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(240))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvInfo)
        loadData()
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun loadData() {
        val ctx=requireContext().applicationContext
        executor.submit {
            try {
                val pm=ctx.packageManager
                val apps=pm.getInstalledApplications(android.content.pm.PackageManager.GET_META_DATA)
                val entries=apps.mapNotNull { app ->
                    val uid=app.uid; val rx=TrafficStats.getUidRxBytes(uid); val tx=TrafficStats.getUidTxBytes(uid)
                    val total=rx+tx; if(total<=0)null
                    else NetTrafficDoughnutChart.AppTraffic(pm.getApplicationLabel(app).toString(),total)
                }.sortedByDescending{it.totalBytes}.take(5)
                val totalRx=TrafficStats.getTotalRxBytes(); val totalTx=TrafficStats.getTotalTxBytes()
                handler.post {
                    if(rootView==null)return@post
                    chart?.setEntries(entries); latestEntries=entries
                    tvInfo?.text="Total since boot:\nDownload: ${fmt(totalRx)}  |  Upload: ${fmt(totalTx)}\n\nTop apps:"
                }
            } catch(_:Exception){}
        }
    }

    private fun fmt(b:Long)=when{b>1073741824->"${"%.1f".format(b/1073741824f)}GB";b>1048576->"${"%.1f".format(b/1048576f)}MB";else->"${"%.0f".format(b/1024f)}KB"}
    override fun getShareText()="Network Traffic per App\n"+latestEntries.joinToString("\n"){"${it.name}: ${fmt(it.totalBytes)}"}+"\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
