package com.example.deviceinfo.feature.cpucore

import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.*
import android.widget.*
import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment
import java.io.BufferedReader
import java.io.FileReader

class CpuCoreFragment : Fragment(), ShareableFragment {

    private var rootView: View? = null
    private var chart: CpuCoreMultiLineChart? = null
    private var tvInfo: TextView? = null
    private var coreCount = 0
    private var prevStats = listOf<LongArray>()
    private val handler = Handler(Looper.getMainLooper())

    private val refreshRunnable = object : Runnable {
        override fun run() {
            if (rootView == null) return
            updateCores()
            handler.postDelayed(this, 1000L)
        }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll = ScrollView(requireContext())
        val root = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.VERTICAL
            val p = dp(12); setPadding(p, p, p, p)
        }
        scroll.addView(root)
        rootView = scroll

        val tvTitle = TextView(requireContext()).apply {
            text = "⚙️ CPU Core Monitor"; textSize = 16f
            setTypeface(null, android.graphics.Typeface.BOLD)
            setPadding(0, 0, 0, dp(8))
        }
        root.addView(tvTitle)

        chart = CpuCoreMultiLineChart(requireContext()).apply {
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(220)
            )
        }
        root.addView(chart)

        tvInfo = TextView(requireContext()).apply {
            textSize = 12f; setPadding(0, dp(8), 0, 0)
            setTextColor(0xFFCCCCCC.toInt())
        }
        root.addView(tvInfo)

        // Legend
        val legend = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.HORIZONTAL
            setPadding(0, dp(6), 0, 0)
        }
        val colors = intArrayOf(0xFF4CAF50.toInt(),0xFF2196F3.toInt(),0xFFFF9800.toInt(),0xFFF44336.toInt(),
            0xFF9C27B0.toInt(),0xFF00BCD4.toInt(),0xFFFFEB3B.toInt(),0xFFFF5722.toInt())
        for (c2 in 0 until (coreCount.coerceAtLeast(8))) {
            val dot = View(requireContext()).apply {
                setBackgroundColor(colors[c2 % colors.size])
                layoutParams = LinearLayout.LayoutParams(dp(12), dp(12)).also { it.setMargins(dp(4),dp(2),dp(2),0) }
            }
            val lbl = TextView(requireContext()).apply {
                text = "C$c2"; textSize = 11f
                layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT).also { it.setMargins(0,0,dp(8),0) }
            }
            legend.addView(dot); legend.addView(lbl)
        }
        root.addView(legend)

        coreCount = Runtime.getRuntime().availableProcessors()
        chart?.initCores(coreCount)
        return scroll
    }

    override fun onResume() { super.onResume(); handler.post(refreshRunnable) }
    override fun onPause()  { super.onPause();  handler.removeCallbacks(refreshRunnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView = null; chart = null }

    private fun updateCores() {
        val stats = readProcStat()
        if (prevStats.isNotEmpty() && stats.size == prevStats.size) {
            val usages = stats.mapIndexed { i, cur ->
                val prev = prevStats[i]
                val totalDiff = cur.sum() - prev.sum()
                val idleDiff  = cur[3] - prev[3]
                if (totalDiff > 0) ((totalDiff - idleDiff) * 100f / totalDiff).coerceIn(0f, 100f)
                else 0f
            }
            chart?.addSample(usages)
            tvInfo?.text = usages.mapIndexed { i, u -> "Core$i: ${u.toInt()}%" }.joinToString("  |  ")
        }
        prevStats = stats
    }

    private fun readProcStat(): List<LongArray> {
        val result = mutableListOf<LongArray>()
        try {
            BufferedReader(FileReader("/proc/stat")).use { reader ->
                reader.lineSequence().forEach { line ->
                    if (line.startsWith("cpu") && line.length > 3 && line[3].isDigit()) {
                        val parts = line.trim().split("\s+".toRegex())
                        val vals = LongArray(parts.size - 1) { parts[it + 1].toLongOrNull() ?: 0L }
                        result.add(vals)
                    }
                }
            }
        } catch (_: Exception) {}
        return result
    }

    override fun getShareText(): String = "CPU Core Monitor — ${coreCount} cores active\nGenerated by CPU-A"
    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()
}
