package com.example.deviceinfo.feature.processmon

import android.app.ActivityManager; import android.content.Context; import android.os.*; import android.view.*
import android.widget.*; import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment
import java.io.BufferedReader; import java.io.FileReader; import java.util.concurrent.Executors

class ProcessMonFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: ProcessAreaChart?=null; private var tvInfo: TextView?=null
    private val executor=Executors.newSingleThreadExecutor(); private val handler=Handler(Looper.getMainLooper())
    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;update();handler.postDelayed(this,3000L)}}

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="⚙️ Process & Thread Monitor";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Blue=System processes  Green=User processes";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=ProcessAreaChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(200))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvInfo)
        update(); return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun update() {
        val ctx=requireContext().applicationContext
        executor.submit {
            val am=ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
            val procs=am.runningAppProcesses ?: emptyList()
            val sysProcs=procs.count{it.importance >= ActivityManager.RunningAppProcessInfo.IMPORTANCE_SERVICE}
            val usrProcs=procs.count{it.importance < ActivityManager.RunningAppProcessInfo.IMPORTANCE_SERVICE}
            val threadCount=try{countThreads()}catch(_:Exception){0}
            val zombies=try{countZombies()}catch(_:Exception){0}
            handler.post {
                if(rootView==null)return@post
                chart?.add(sysProcs,usrProcs)
                tvInfo?.text="Total processes: ${procs.size}  (System: $sysProcs  User: $usrProcs)\nTotal threads: $threadCount\nZombie processes: $zombies\nForeground: ${procs.count{it.importance==ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND}}"
            }
        }
    }

    private fun countThreads(): Int {
        var count=0
        try {
            java.io.File("/proc").listFiles()?.filter{it.name.matches(Regex("\\d+"))}?.forEach{dir->
                dir.listFiles()?.filter{it.name.matches(Regex("\\d+"))}?.let{count+=it.size}
            }
        } catch(_:Exception){}
        return count
    }

    private fun countZombies(): Int {
        var count=0
        try {
            java.io.File("/proc").listFiles()?.filter{it.name.matches(Regex("\\d+"))}?.forEach{dir->
                try{
                    val stat=BufferedReader(FileReader("${dir.path}/status")).use{it.readLines()}
                    if(stat.any{it.startsWith("State:")&&it.contains("Z")})count++
                }catch(_:Exception){}
            }
        } catch(_:Exception){}
        return count
    }

    override fun getShareText()="Process Monitor\n${tvInfo?.text}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
