package com.example.deviceinfo.feature.pingmonitor

import android.os.*
import android.view.*
import android.widget.*
import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment
import java.net.InetAddress
import java.util.concurrent.Executors

class PingMonitorFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null
    private var chart: PingLineChart? = null
    private var tvStats: TextView? = null
    private val executor = Executors.newFixedThreadPool(3)
    private val handler = Handler(Looper.getMainLooper())
    private val pingResults = Array(3) { mutableListOf<Float>() }

    private val pingRunnable = object : Runnable {
        override fun run() {
            if (rootView == null) return
            pingAll()
            handler.postDelayed(this, 3000L)
        }
    }

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll = ScrollView(requireContext())
        val root = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.VERTICAL; val p = dp(12); setPadding(p, p, p, p)
        }
        scroll.addView(root); rootView = scroll

        root.addView(TextView(requireContext()).apply {
            text = "📡 Network Latency Monitor"; textSize = 16f
            setTypeface(null, android.graphics.Typeface.BOLD); setPadding(0,0,0,dp(6))
        })
        chart = PingLineChart(requireContext()).apply {
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(220))
        }
        root.addView(chart)
        tvStats = TextView(requireContext()).apply { textSize = 12f; setPadding(0,dp(8),0,0) }
        root.addView(tvStats)
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(pingRunnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(pingRunnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView = null; chart = null }

    private fun pingAll() {
        val hosts = chart?.getHosts() ?: return
        hosts.forEachIndexed { idx, host ->
            executor.submit {
                val ms = ping(host)
                handler.post {
                    if (rootView == null) return@post
                    chart?.addSample(idx, ms)
                    pingResults[idx].add(ms)
                    if (pingResults[idx].size > 30) pingResults[idx].removeAt(0)
                    updateStats()
                }
            }
        }
    }

    private fun ping(host: String): Float {
        return try {
            val t0 = System.currentTimeMillis()
            val addr = InetAddress.getByName(host)
            val ok = addr.isReachable(2000)
            if (ok) (System.currentTimeMillis() - t0).toFloat() else 999f
        } catch (_: Exception) { 999f }
    }

    private fun updateStats() {
        val hosts = chart?.getHosts() ?: return
        val sb = StringBuilder()
        hosts.forEachIndexed { i, h ->
            val data = pingResults[i]
            if (data.isNotEmpty()) {
                val valid = data.filter { it < 900f }
                val avg = if (valid.isNotEmpty()) valid.average() else 0.0
                val loss = data.count { it >= 900f } * 100 / data.size
                sb.appendLine("$h → Avg: ${"%.0f".format(avg)}ms  Loss: $loss%  Min: ${valid.minOrNull()?.toInt() ?: 0}ms  Max: ${valid.maxOrNull()?.toInt() ?: 0}ms")
            }
        }
        tvStats?.text = sb.toString()
    }

    override fun getShareText() = "Network Latency Monitor
${tvStats?.text}
Generated by CPU-A"
    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()
}
