package com.cpua.deviceinfo.feature.bootspeed

import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment; import com.cpua.deviceinfo.core.ui.ShareableFragment

class BootSpeedFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: BootSpeedBarChart?=null; private var tvInfo: TextView?=null

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="⚡ Boot Speed Tracker";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Green<10s  Orange<20s  Red=slow  |  Yellow=avg line";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=BootSpeedBarChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(220))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvInfo)
        loadData()
        // Record this boot session
        val uptimeSec = SystemClock.elapsedRealtime() / 1000f
        BootSpeedManager.recordBoot(requireContext(), uptimeSec)
        loadData()
        return scroll
    }

    private fun loadData() {
        val entries=BootSpeedManager.getAll(requireContext())
        chart?.setEntries(entries)
        val uptimeSec=SystemClock.elapsedRealtime()/1000f
        val uptimeHours=uptimeSec/3600
        val fastest=entries.minByOrNull{it.seconds}; val slowest=entries.maxByOrNull{it.seconds}
        tvInfo?.text="Current uptime: ${"%.1f".format(uptimeSec)}s since last boot (${"%.1f".format(uptimeHours)}h)\nFastest boot: ${fastest?.let{"${it.seconds.toInt()}s on ${it.label}"}?:"—"}\nSlowest boot: ${slowest?.let{"${it.seconds.toInt()}s on ${it.label}"}?:"—"}\n📊 ${entries.size} boot sessions recorded\nNote: uptime = time from power-on to app open"
    }

    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }
    override fun getShareText()="Boot Speed Tracker\n${tvInfo?.text}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
