package com.example.deviceinfo.feature.powerestimate

import android.app.ActivityManager; import android.content.*; import android.net.TrafficStats; import android.os.*
import android.view.*; import android.widget.*; import androidx.fragment.app.Fragment
import com.example.deviceinfo.core.ui.ShareableFragment; import java.io.BufferedReader; import java.io.FileReader

class PowerEstimateFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: PowerPieChart?=null; private var tvTotal: TextView?=null
    private val handler=Handler(Looper.getMainLooper())
    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;estimate();handler.postDelayed(this,5000L)}}
    private var lastRx=0L; private var lastTx=0L; private var lastTs=0L

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="⚡ Power Consumption Estimator";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Estimated from CPU freq, RAM, network & screen";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=PowerPieChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(280))}
        root.addView(chart)
        tvTotal=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvTotal)
        estimate(); return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun estimate() {
        // CPU power: estimate from freq% × TDP (assume 3W max TDP for mobile)
        val cpuFreqPct = try {
            val cur=BufferedReader(FileReader("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq")).use{it.readLine()?.toLongOrNull()?:0L}
            val max=BufferedReader(FileReader("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")).use{it.readLine()?.toLongOrNull()?:1L}
            (cur*100f/max).coerceIn(0f,100f)
        } catch(_:Exception){50f}
        val cpuMw=(cpuFreqPct/100f)*3000f
        // RAM power: ~0.3W per GB used
        val am=requireContext().getSystemService(android.content.Context.ACTIVITY_SERVICE) as ActivityManager
        val mi=ActivityManager.MemoryInfo().also{am.getMemoryInfo(it)}
        val ramUsedGb=(mi.totalMem-mi.availMem)/1073741824f
        val ramMw=ramUsedGb*300f
        // Network power: ~600mW when active
        val now=System.currentTimeMillis()
        val rx=TrafficStats.getTotalRxBytes(); val tx=TrafficStats.getTotalTxBytes()
        val netActive=if(lastTs>0){val dt=(now-lastTs)/1000f;((rx-lastRx+tx-lastTx)/dt)>1024}else false
        lastRx=rx;lastTx=tx;lastTs=now
        val netMw=if(netActive)600f else 50f
        // Screen power: estimate ~800mW when screen is on
        val screenMw=800f
        // Standby baseline ~200mW
        val otherMw=200f
        val slices=listOf(
            PowerPieChart.Slice("CPU",cpuMw,0xFF4CAF50.toInt()),
            PowerPieChart.Slice("RAM",ramMw,0xFF2196F3.toInt()),
            PowerPieChart.Slice("Screen",screenMw,0xFFFF9800.toInt()),
            PowerPieChart.Slice("Network",netMw,0xFFF44336.toInt()),
            PowerPieChart.Slice("System",otherMw,0xFF9C27B0.toInt())
        )
        chart?.setSlices(slices)
        val total=(cpuMw+ramMw+screenMw+netMw+otherMw)/1000f
        // Get actual current from BatteryManager
        val bm=requireContext().getSystemService(android.content.Context.BATTERY_SERVICE) as BatteryManager
        val actualCurrentMa=kotlin.math.abs(bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CURRENT_NOW)/1000)
        val battIntent=requireContext().registerReceiver(null,IntentFilter(Intent.ACTION_BATTERY_CHANGED))
        val voltMv=battIntent?.getIntExtra(BatteryManager.EXTRA_VOLTAGE,3800)?:3800
        val actualW=if(actualCurrentMa>0)(actualCurrentMa*voltMv)/1_000_000f else total
        tvTotal?.text="Estimated total: ${"%.2f".format(total)}W
Actual (BatteryManager): ${"%.2f".format(actualW)}W  (${actualCurrentMa}mA @ ${voltMv}mV)
CPU: ${"%.2f".format(cpuMw/1000f)}W (${cpuFreqPct.toInt()}% freq)  RAM used: ${"%.1f".format(ramUsedGb)}GB
Network: ${if(netActive)"Active ≈600mW" else "Idle ≈50mW"}"
    }

    override fun getShareText()="Power Estimator
${tvTotal?.text}
Generated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
