package com.example.deviceinfo.core.util

  import android.content.ContentValues
  import android.content.Context
  import android.graphics.Canvas
  import android.graphics.Color
  import android.graphics.Paint
  import android.graphics.pdf.PdfDocument
  import android.os.Build
  import android.os.Environment
  import android.provider.MediaStore
  import android.widget.Toast
  import java.io.File
  import java.io.FileOutputStream
  import java.io.OutputStream
  import java.text.SimpleDateFormat
  import java.util.Date
  import java.util.Locale

  object ExportUtils {

      /** Export a single tab's data as a .txt file */
      fun exportToFile(context: Context, tabName: String, data: Map<String, String>) {
          val ts = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
          val filename = "DeviceInfo_${tabName}_$ts.txt"
          val content = buildString {
              appendLine("CPU-A Device Info — $tabName")
              appendLine("Exported: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}")
              appendLine("─".repeat(40))
              data.forEach { (k, v) -> appendLine("$k: $v") }
          }
          writeText(context, filename, content)
      }

      /** Export ALL tabs combined into one .txt file (called from AboutFragment) */
      fun exportAllToFile(context: Context, allData: Map<String, Map<String, String>>) {
          val ts = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
          val filename = "DeviceInfo_Full_Report_$ts.txt"
          val content = buildString {
              appendLine("CPU-A Device Info — Full Device Report")
              appendLine("Exported: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}")
              appendLine("═".repeat(50))
              appendLine()
              allData.forEach { (tab, data) ->
                  appendLine("[ $tab ]")
                  appendLine("─".repeat(40))
                  data.forEach { (k, v) -> appendLine("  $k: $v") }
                  appendLine()
              }
              appendLine("─────────────────────────────────────────")
              appendLine("Generated by CPU-A Device Info app")
          }
          writeText(context, filename, content)
      }

      private fun writeText(context: Context, filename: String, content: String) {
          try {
              val stream = openOutputStream(context, filename, "text/plain", Environment.DIRECTORY_DOCUMENTS)
              stream?.use { it.write(content.toByteArray()) }
              Toast.makeText(context, "Exported: $filename", Toast.LENGTH_LONG).show()
          } catch (e: Exception) {
              Toast.makeText(context, "Export failed: ${e.message}", Toast.LENGTH_SHORT).show()
          }
      }

      /** Export a single tab as PDF to Downloads folder */
      fun exportToPdf(context: Context, tabName: String, data: Map<String, String>) {
          val ts = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
          val filename = "DeviceInfo_${tabName}_$ts.pdf"

          val pageWidth  = 595
          val pageHeight = 842
          val margin     = 48f
          val lineHeight = 22f

          val paintTitle   = Paint().apply { color = Color.parseColor("#006064"); textSize = 20f; isFakeBoldText = true; isAntiAlias = true }
          val paintSub     = Paint().apply { color = Color.parseColor("#0097A7"); textSize = 11f; isFakeBoldText = true; isAntiAlias = true }
          val paintLabel   = Paint().apply { color = Color.parseColor("#546E7A"); textSize = 12f; isAntiAlias = true }
          val paintValue   = Paint().apply { color = Color.parseColor("#1A1A2E"); textSize = 12f; isFakeBoldText = true; isAntiAlias = true }
          val paintDivider = Paint().apply { color = Color.parseColor("#B2EBF2"); strokeWidth = 1f }

          val doc = PdfDocument()
          var pageNum    = 1
          var yPos       = margin + 80f
          var activePage : PdfDocument.Page? = null
          var canvas     : Canvas? = null

          fun endPage() {
              activePage?.let { doc.finishPage(it) }
              activePage = null; canvas = null
          }
          fun startPage(firstPage: Boolean = false) {
              val pi = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum++).create()
              activePage = doc.startPage(pi)
              canvas = activePage!!.canvas
              yPos = if (firstPage) margin + 80f else margin + 20f
          }

          startPage(firstPage = true)
          canvas!!.drawText("CPU-A Device Info", margin, margin + 30f, paintTitle)
          canvas!!.drawText("Tab: $tabName", margin, margin + 50f, paintSub)
          canvas!!.drawText(
              "Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}",
              margin, margin + 68f, paintLabel
          )
          canvas!!.drawLine(margin, margin + 74f, pageWidth - margin, margin + 74f, paintDivider)

          for ((key, value) in data) {
              if (yPos + lineHeight > pageHeight - margin) { endPage(); startPage() }
              canvas!!.drawText(key,            margin,            yPos, paintLabel)
              canvas!!.drawText(value,          pageWidth / 2f,    yPos, paintValue)
              canvas!!.drawLine(margin, yPos + 4f, pageWidth - margin, yPos + 4f, paintDivider)
              yPos += lineHeight
          }
          endPage()

          try {
              val stream = openOutputStream(context, filename, "application/pdf", Environment.DIRECTORY_DOWNLOADS)
              stream?.use { doc.writeTo(it) }
              Toast.makeText(context, "PDF saved: $filename", Toast.LENGTH_LONG).show()
          } catch (e: Exception) {
              Toast.makeText(context, "PDF failed: ${e.message}", Toast.LENGTH_SHORT).show()
          } finally {
              doc.close()
          }
      }

      private fun openOutputStream(context: Context, filename: String, mimeType: String, dir: String): OutputStream? {
          return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
              val values = ContentValues().apply {
                  put(MediaStore.MediaColumns.DISPLAY_NAME, filename)
                  put(MediaStore.MediaColumns.MIME_TYPE, mimeType)
                  put(MediaStore.MediaColumns.RELATIVE_PATH, dir)
              }
              val uri = if (mimeType == "application/pdf")
                  MediaStore.Downloads.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY)
              else
                  MediaStore.Files.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY)
              context.contentResolver.insert(uri, values)?.let { context.contentResolver.openOutputStream(it) }
          } else {
              @Suppress("DEPRECATION")
              val folder = Environment.getExternalStoragePublicDirectory(dir)
              folder.mkdirs()
              FileOutputStream(File(folder, filename))
          }
      }
  }