package com.example.deviceinfo.feature.brightness

import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment

class BrightnessFragment : Fragment(), ShareableFragment {
    private var rootView: View?=null; private var chart: BrightnessStepChart?=null; private var tvInfo: TextView?=null
    private val handler=Handler(Looper.getMainLooper())
    private val runnable=object:Runnable{override fun run(){if(rootView==null)return;update();handler.postDelayed(this,2000L)}}
    private val history=mutableListOf<Pair<Long,Int>>()

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll=ScrollView(requireContext()); val root=LinearLayout(requireContext()).apply{orientation=LinearLayout.VERTICAL;val p=dp(12);setPadding(p,p,p,p)}
        scroll.addView(root); rootView=scroll
        root.addView(TextView(requireContext()).apply{text="☀️ Display Brightness Timeline";textSize=16f;setTypeface(null,android.graphics.Typeface.BOLD);setPadding(0,0,0,dp(6))})
        root.addView(TextView(requireContext()).apply{text="Step line = brightness changes  |  Yellow = brightness level";textSize=11f;alpha=0.7f;setPadding(0,0,0,dp(4))})
        chart=BrightnessStepChart(requireContext()).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(200))}
        root.addView(chart)
        tvInfo=TextView(requireContext()).apply{textSize=12f;setPadding(0,dp(8),0,0);setTextColor(0xFFCCCCCC.toInt())}
        root.addView(tvInfo)
        update(); return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView=null; chart=null }

    private fun update() {
        val ctx=context?:return
        val brightness=try{Settings.System.getInt(ctx.contentResolver,Settings.System.SCREEN_BRIGHTNESS)}catch(_:Exception){128}
        val autoMode=try{Settings.System.getInt(ctx.contentResolver,Settings.System.SCREEN_BRIGHTNESS_MODE)==Settings.System.SCREEN_BRIGHTNESS_MODE_AUTOMATIC}catch(_:Exception){false}
        chart?.add(brightness)
        history.add(System.currentTimeMillis() to brightness)
        if(history.size>100)history.removeAt(0)
        val avg=history.map{it.second}.average()
        val changes=history.zipWithNext().count{(a,b)->kotlin.math.abs(a.second-b.second)>10}
        tvInfo?.text="Current: $brightness / 255  (${brightness*100/255}%)\nAuto brightness: ${if(autoMode)"On" else "Off"}\nAvg in session: ${"%.0f".format(avg)}/255  |  Changes detected: $changes"
    }

    override fun getShareText()="Brightness Timeline\n${tvInfo?.text}\nGenerated by CPU-A"
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
