package com.example.deviceinfo.feature.wifichannel

import android.content.Context; import android.net.wifi.*; import android.os.*; import android.view.*; import android.widget.*
import androidx.fragment.app.Fragment; import com.example.deviceinfo.core.ui.ShareableFragment

class WifiChannelFragment : Fragment(), ShareableFragment {
    private var rootView: View? = null; private var chart: WifiSpectrumChart? = null; private var tvInfo: TextView? = null
    private val handler = Handler(Looper.getMainLooper())
    private val runnable = object : Runnable {
        override fun run() { if (rootView == null) return; scanWifi(); handler.postDelayed(this, 8000L) }
    }
    private var latestNetworks = listOf<WifiSpectrumChart.Network>()

    override fun onCreateView(i: LayoutInflater, c: ViewGroup?, s: Bundle?): View {
        val scroll = ScrollView(requireContext()); val root = LinearLayout(requireContext()).apply {
            orientation = LinearLayout.VERTICAL; val p = dp(12); setPadding(p, p, p, p) }
        scroll.addView(root); rootView = scroll
        root.addView(TextView(requireContext()).apply { text = "📶 WiFi Channel Analyzer"; textSize = 16f
            setTypeface(null, android.graphics.Typeface.BOLD); setPadding(0, 0, 0, dp(6)) })
        root.addView(TextView(requireContext()).apply { text = "Green = Your network  |  Taller bar = stronger signal"; textSize = 11f; alpha = 0.7f; setPadding(0,0,0,dp(4)) })
        chart = WifiSpectrumChart(requireContext()).apply {
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(240)) }
        root.addView(chart)
        tvInfo = TextView(requireContext()).apply { textSize = 11f; setPadding(0, dp(8), 0, 0); setTextColor(0xFFCCCCCC.toInt()) }
        root.addView(tvInfo)
        val btnScan = Button(requireContext()).apply { text = "Scan Now"; setOnClickListener { scanWifi() } }
        root.addView(btnScan)
        return scroll
    }

    override fun onResume()  { super.onResume();  handler.post(runnable) }
    override fun onPause()   { super.onPause();   handler.removeCallbacks(runnable) }
    override fun onDestroyView() { super.onDestroyView(); rootView = null; chart = null }

    private fun scanWifi() {
        try {
            val wm = requireContext().applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager
            val myBssid = wm.connectionInfo?.bssid ?: ""
            val results = wm.scanResults ?: emptyList()
            fun freqToChannel(f: Int) = when {
                f in 2412..2484 -> (f - 2412) / 5 + 1
                f in 5170..5825 -> (f - 5000) / 5
                else -> 0
            }
            latestNetworks = results.map { WifiSpectrumChart.Network(
                ssid = it.SSID.ifEmpty { "<Hidden>" }, channel = freqToChannel(it.frequency),
                rssi = it.level, freq = it.frequency, isMine = it.BSSID == myBssid) }
            chart?.setNetworks(latestNetworks)
            val congestion24 = latestNetworks.count { it.freq < 3000 }
            val congestion5  = latestNetworks.count { it.freq >= 3000 }
            val myNet = latestNetworks.firstOrNull { it.isMine }
            tvInfo?.text = "Found ${latestNetworks.size} networks\n2.4GHz: $congestion24 networks  |  5GHz: $congestion5 networks\nYour network: ${myNet?.ssid ?: "Unknown"} Ch${myNet?.channel ?: "?"} ${myNet?.rssi ?: 0}dBm"
        } catch (e: SecurityException) {
            tvInfo?.text = "Location permission needed for WiFi scan.\n(Required by Android for WiFi scan results)"
        }
    }

    override fun getShareText() = "WiFi Channel Analyzer — ${latestNetworks.size} networks found\n${tvInfo?.text}\nGenerated by CPU-A"
    private fun dp(v: Int) = (v * resources.displayMetrics.density).toInt()
}
